version: "3.11"
services:

  backend:
    image: leenominai/test_nova_backend
    container_name: test_backend
    restart: always
    volumes:
      - static_value:/backend/static/
      - media_value:/backend/media/
    ports:
      - "8000:8000"
    env_file:
      - ./.env


  nginx:
    image: nginx:1.21.3-alpine
    container_name: test_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - backend


volumes:
  static_value:
  media_value:
